version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  veteran-employment-center:
    build:
      context: .
      args:
        database_password: "password"
    image: "veteran-employment-center:${DOCKER_IMAGE:-latest}"
    volumes:
      - .:/src/vec
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST:-postgres}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      LC_ALL: "en_US.UTF-8"
    depends_on:
      - postgres
    links:
      - postgres
    tty: true
